# Generated by Django 5.2.6 on 2025-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="number_of_traps",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
