# Generated by Django 5.2.6 on 2025-09-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_location_user_number_of_traps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
