# Generated by Django 5.2.6 on 2025-09-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamonitoring',
            old_name='level_reading',
            new_name='trap_fill_level',
        ),
        migrations.AddField(
            model_name='datamonitoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
